# Generated by Django 5.0.6 on 2024-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_event_category_recipe_category_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, to='community.recipecategory'),
        ),
    ]
