# Generated by Django 5.0.6 on 2024-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='community.eventcategory'),
        ),
    ]
